cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_details, name="details"),
    path("add/<int:id>/", views.cart_add, name="add_cart"),
    path("remove/<int:id>/", views.cart_remove, name="remove"),
    path("show/", views.cart_show, name="show"),
    path("add-single/<int:id>/", views.add_single, name="add-single"),
    path("remove_single/<int:id>/", views.remove_single, name="remove_single"),
    path("update-cart", views.updatecart, name="updatecart"),
    path("provinces-json/", views.get_json_province_data, name="provinces-json"),
    path("city-json/<str:city>/", views.get_json_city_data, name="models-json"),
    path("cart-count/", views.ItemcountView.as_view(), name="cart-count"),
]

home/urls.py
from django.urls import path

from . import views

app_name='home'
urlpatterns = [
    path('',views.home,name='home'),
    path('product/',views.all_product,name='product'),
    path('detail/<int:id>/',views.product_detail,name='detail'),
    path('category/<slug>/<int:id>',views.all_product,name='category'),
    path('like/<int:id>',views.product_like,name='product_like'),
    path('unlike/<int:id>',views.product_unlike,name='product_unlike'),
    path('comment/<int:id>',views.product_Comment,name='product_Comment'),
    path('reply/<int:id>/<int:comment_id>/',views.product_reply,name='product_reply'),
    path('like_comment/<int:id>',views.comment_like,name='comment_like'),
    path('search/',views.product_search,name='product_search'),
    path('favourite/<int:id>/',views.favourite_product,name='favourite'),
    path('contact/',views.contact,name='contact'),
    path('compare/',views.compare,name='compare'),
    path('about/',views.about,name='about'),
    path('add/<int:product_id>',views.add_compare,name='add'),
    path('remove/<int:product_id>',views.remove_compare,name='remove'),
    path('favourite/<int:id>', views.favourite_product, name='favourite'),
    path('blogs/', views.blog_list, name='blog_list'),  # A page listing all blogs
    path('blogs/<int:pk>/', views.blog_detail, name='blog_detail'),  # Detailed view for each blog
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.sitemaps import ProductViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'product' : ProductViewSitemap,
}


urlpatterns = [


  path('admin/', admin.site.urls),
  path('', include('home.urls', namespace='home')),
  path('accounts/', include('accounts.urls', namespace='accounts')),
  path('ckeditor/', include('ckeditor_uploader.urls')),
  path('cart/', include('cart.urls', namespace='cart')),
  path('order/', include('order.urls', namespace='order')),
  path('sitemaps.xml',sitemap,{'sitemaps':sitemaps})

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

home/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=30)

home/views.py
from django.shortcuts import render,get_object_or_404,redirect
from urllib3 import request

from .models import *
from django.http import HttpResponse
from django.contrib import messages
from .forms import *
from cart.forms import *
from django.db.models import Q,Max,Min,Count,Sum
from cart.models import *
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from .filters import ProductFilter
from urllib.parse import urlencode
from .compare import Compare
from django.http import JsonResponse
from django.db.models import Case, When, Value, IntegerField

def home(request):
    category = Category.objects.filter(sub_cat=False)
    gallery = Gallery.objects.all()
    
    # Annotate each product with an "availability_order" field:
    # available products (amount != 0) get 0 and unavailable (amount == 0) get 1.
    create = Product.objects.annotate(
        availability_order=Case(
            When(amount=0, then=Value(1)),
            default=Value(0),
            output_field=IntegerField()
        )
    ).order_by('availability_order', '-create')
    
    max_discount = Product.objects.all().order_by('-discount')[:6]
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    latest_blogs = Blog.objects.all().order_by('-published_date')[:3]
    return render(request, 'home/home.html', {
        'max_discount': max_discount,
        'category': category,
        'gallery': gallery,
        'create': create,
        'nums': nums,
        'latest_blogs': latest_blogs,
    })
# def home(request):
#     category = Category.objects.filter(sub_cat=False)
#     gallery = Gallery.objects.all()
#     # create = Variants.objects.all().order_by('-create')[:6]
#     # create = Variants.objects.all()
#     # max_discount = Variants.objects.all().order_by('-discount')[:6]
#     create = Product.objects.all()
#     max_discount = Product.objects.all().order_by('-discount')[:6]
#     nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
#     return render(request,'home/home.html',{'max_discount':max_discount,'category':category,'gallery':gallery,'create':create,
#                                             'nums':nums})

def all_product(request,slug=None,id=None):
    products = Product.objects.all()
    variant = Variants.objects.all()
    price_agg = Product.objects.aggregate(
    min_price=Min('unit_price'),
    max_price=Max('unit_price'),)

    min_price = int(price_agg.get('min_price') or 0)
    max_price = int(price_agg.get('max_price') or 0)

    filter = ProductFilter(request.GET,queryset=products)
    products = filter.qs
    paginator = Paginator(products,8)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)
    category = Category.objects.filter(sub_cat=False)

    if slug and id:
        data = get_object_or_404(Category,slug=slug,id=id)
        page_obj = products.filter(category=data)
        paginator = Paginator(page_obj, 8)
        page_num = request.GET.get('page')
        page_obj = paginator.get_page(page_num)
    s_form = SearchForm()
    if 'search' in request.GET:
        s_form = SearchForm(request.GET)
        if s_form.is_valid():
            info = s_form.cleaned_data['search']
            page_obj = products.filter(Q(name__icontains=info))
            paginator = Paginator(page_obj, 8)
            page_num = request.GET.get('page')
            data = request.GET.copy()
            if 'page' in data:
                del data['page']
            page_obj = Paginator.get_page(page_num)



    return render(request,'home/product.html',{'variant':variant,'products':page_obj,'category':category,'s_form':s_form,
                                               'page_num':page_num,'filter':filter,'min_price':min_price,'max_price':max_price,
                                              })

def product_detail(request,id):
    product = get_object_or_404(Product,id=id)
    form = CartAddForm()
    ip = request.META.get('REMOTE_ADDR')
    view = Views.objects.filter(product_id=product.id,ip=ip)
    if not view.exists():
        Views.objects.create(product_id=product.id,ip=ip)
        product.num_view +=1
        product.save()
    if request.user.is_authenticated:
        product.view.add(request.user)
    update = Chart.objects.filter(product_id=id)
    change = Chart.objects.all()
    images = Images.objects.filter(product_id=id)
    comment_form = CommentForm()
    reply_form = ReplayForm()
    cart_form = CartForm()
    comment = Commnet.objects.filter(product_id=id,is_reply=False)
    similar = product.tags.similar_objects()[:2]
    is_favourite = False
    if product.favourite.filter(id=request.user.id).exists():
        is_favourite=True
    is_like =False
    if product.like.filter(id=request.user.id).exists():
        is_like = True
    is_unlike = False
    if product.unlike.filter(id=request.user.id).exists():
        is_unlike = True


    if product.status != 'None':
        if request.method == 'POST':
            variant = Variants.objects.filter(product_variant_id=id)
            var_id = request.POST.get('select')
            variants = Variants.objects.get(id=var_id)
            colors = Variants.objects.filter(product_variant_id=id,size_variant_id=variants.size_variant_id)
            size= Variants.objects.raw(
                'SELECT * FROM home_variants WHERE product_variant_id=%s GROUP BY size_variant_id',[id])

            # sizes = Variants.objects.filter(product_variant_id=id).distinct('size_variant_id') #for postgresql
        else:
            variant = Variants.objects.filter(product_variant_id=id)
            variants = Variants.objects.get(id=variant[0].id)
            colors = Variants.objects.filter(product_variant_id=id, size_variant_id=variants.size_variant_id)
            size = Variants.objects.raw(
                'SELECT * FROM home_variants WHERE product_variant_id=%s GROUP BY size_variant_id', [id])

        context = {'product':product,'variant':variant,'variants':variants,'similar':similar,'is_like':is_like,'comment_form':comment_form,
                   'comment':comment,'reply_form':reply_form,'images':images,'is_unlike':is_unlike,'cart_form':cart_form,'is_favourite':is_favourite,'change':change,'colors':colors,'size':size,'form':form}
        return render(request, 'home/details.html', context)
    else:
        return render(request,'home/details.html',{'product':product,'similar':similar,
                                                   'is_like':is_like,'comment_form':comment_form,'comment':comment,'reply_form':reply_form,
                                                   'images':images,'is_unlike':is_unlike,'cart_form':cart_form,'is_favourite':is_favourite,'update':update,'form':form})


def product_like(request,id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product,id=id)
    is_like = False
    if product.like.filter(id=request.user.id).exists():
        product.like.remove(request.user)
        is_like = False
        messages.success(request,'remove','success')
    else:
        product.like.add(request.user)
        is_like = True
        messages.success(request, 'add', 'success')
    return redirect(url)


def product_unlike(request,id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product,id=id)
    product.unlike.add(request.user)
    messages.success(request, 'add like', 'dark')
    return redirect(url)




def product_Comment(request,id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        comment_Form = CommentForm(request.POST)
        if comment_Form.is_valid():
            data = comment_Form.cleaned_data
            Commnet.objects.create(comment=data['comment'],rate=data['rate'],user_id=request.user.id,product_id=id)
        return redirect(url)

def product_reply(request,id,comment_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        reply_form = ReplayForm(request.POST)
        if reply_form.is_valid():
            data = reply_form.cleaned_data
            Commnet.objects.create(comment=data['comment'],product_id=id,user_id=request.user.id,reply_id=comment_id,is_reply=True)
            messages.success(request,'tnx for reply','primary')
            return redirect(url)

def comment_like(request,id):
    url = request.META.get('HTTP_REFERER')
    comment = Commnet.objects.get(id=id)
    if comment.comment_like.filter(id=request.user.id).exists():
        comment.comment_like.remove(request.user)
    else:
        comment.comment_like.add(request.user)
        messages.success(request,'tnx for like','warning')
    return JsonResponse({'success':'ok'})


def product_search(request):
    products = Product.objects.all()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['search']
            if data.isdigit():
                products = products.filter(Q(discount__exact=data)|Q(unit_price__exact=data))
            else:
                products = products.filter(Q(name__icontains=data))
            return render(request,'home/product.html',{'products':products,'form':form})



def favourite_product(request,id):
    url =request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=id)
    is_favourite = False
    if product.favourite.filter(id=request.user.id).exists():
        product.favourite.remove(request.user)
        product.total_favourite -=1
        product.save()
        is_favourite = False
    else:
        product.favourite.add(request.user)
        product.total_favourite += 1
        product.save()
        is_favourite = True
    return redirect(url)

def contact(request):
    if request.method == 'POST':
        subject = request.POST['subject']
        email = request.POST['email']
        msg = request.POST['message']

home/templates/home/blog.html
{% extends 'base.html' %}
{% block title %}
    مقالات
{% endblock %}
{% load static %}
{% block body %}
    
     <!-- Breadcrumb Area Start -->
    <div class="section breadcrumb-area bg-bright">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="breadcrumb-wrapper">
                        <h2 class="breadcrumb-title">مقالات</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End -->

    <!-- Blog Grid Section Start -->
    <div class="section section-margin">
        <div class="container">
            <div class="row row-cols-lg-3 row-cols-sm-2 row-cols-1 mb-n8">
                {% for blog in blogs %}

                <div class="col mb-8">
                    <!-- Single Blog Start -->
                    <div class="single-blog-wrapper">

                        <!-- Blog Thumb Start -->
                        <div class="blog-thumb thumb-effect">
                            <a class="image" href="{% url 'home:blog_detail' blog.pk %}">
                                <img class="fit-image" src="{{ blog.image.url }}" alt="{{ blog.title }}">
                            </a>
                        </div>
                        <!-- Blog Thumb End -->

                        <!-- Blog Content Start -->
                        <div class="blog-content">
                            <div class="blog-meta">
                                <ul>
                                    <li><span>{{ blog.published_date }}</span></li>
                                </ul>
                            </div>
                            <h2 class="blog-title"><a href="{% url 'home:blog_detail' blog.pk %}">{{ blog.title }}</a></h2>
                            <p>{{ blog.description|truncatewords:20 }}</p>
                            <a class="more-link" href="{% url 'home:blog_detail' blog.pk %}">خواندن مقاله</a>
                        </div>
                        <!-- Blog Content End -->

                    </div>
                    <!-- Single Blog End -->
                </div>
                {% endfor %}


            </div>
{#            <div class="row">#}
{#                <div class="col-12 mt-10">#}
{#                    <nav class="d-flex justify-content-center">#}
{#                        <ul class="pagination">#}
{#                            <li class="page-item"><a class="page-link active" href="#/">1</a></li>#}
{#                            <li class="page-item"><a class="page-link" href="#/">2</a></li>#}
{#                            <li class="page-item"><a class="page-link" href="#/">3</a></li>#}
{#                            <li class="page-item">#}
{#                                <a class="page-link rounded-0" href="#/" aria-label="Next">#}
{#                                    <span aria-hidden="true">&raquo;</span>#}
{#                                </a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </nav>#}
{#                </div>#}
{#            </div>#}
        </div>
    </div>
    <!-- Blog Grid Section End -->
    

 <!-- Scroll Top Start -->
    <a href="#" class="scroll-top show" id="scroll-top">
        <i class="arrow-top ti-angle-double-up"></i>
        <i class="arrow-bottom ti-angle-double-up"></i>
    </a>
    <!-- Scroll Top End -->

     <!-- Mobile Menu Start -->
    <div class="mobile-menu-wrapper">
        <div class="offcanvas-overlay"></div>

        <!-- Mobile Menu Inner Start -->
        <div class="mobile-menu-inner">

            <!-- Button Close Start -->
            <div class="offcanvas-btn-close">
                <i class="fa fa-times"></i>
            </div>
            <!-- Button Close End -->

            <!-- Mobile Menu Inner Wrapper Start -->
            <div class="mobile-menu-inner-wrapper">


                <!-- Mobile Menu Start -->
                <div class="mobile-navigation">
                    <nav>
                        <ul class="mobile-menu">
                            <li class="has-children">
                                <a href="{% url 'home:home' %}">خانه </a>
                            </li>
                            {% for data in category %}
                                <li class="has-children">
                                    <a href="#"> {{ data.name }}<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                                    <ul class="dropdown">
                                        {% for info in data.sub.all %}
                                            <li><a href="{{ info.get_absolute_url }}">{{ info.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}
{#                            <li class="has-children">#}
{#                                <a href="{% url 'home:product' %}">فروشگاه </a>#}
{#                            </li>#}
                            <li class="has-children">
                                <a href="{% url 'home:blog_list' %}">آموزش</a>
                            </li>
                            <li class="has-children">
                                <a href="{% url 'home:about' %}">درباره ما</a>
                            </li>
                            <li class="has-children">
                                <a href="{% url 'home:contact' %}">تماس با ما</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!-- Mobile Menu End -->


                <!-- Contact Links/Social Links Start -->
                <div class="mt-auto bottom-0">

                    <!-- Contact Links Start -->
                    <ul class="contact-links">
                        <li><i class="fa fa-phone"></i><a href="#" class="mx-1"> 0919-877-1017</a></li>
                        <li><i class="fa fa-envelope-o"></i><a href="#" class="mx-1"> petshoproyal.co@gmail.com</a></li>
                        <li><i class="fa fa-clock-o"></i> <span class="mx-1">هر روز هفته ، هر ساعت روز</span></li>
                    </ul>
                    <!-- Contact Links End -->

                    <!-- Social Widget Start -->
                    <div class="widget-social">
                        <a title="Telegram" href="https://t.me/PetshopRoyal1"><i class="fa fa-telegram"></i></a>
                        <a title="Instagram" href="https://instagram.com/petshop_royal1"><i class="icon-social-instagram"></i></a>
                        <a title="Whatsapp" href="https://wa.link/m35ti7"><i class="fa fa-whatsapp"></i></a>
                    </div>
                    <!-- Social Widget Ender -->
                </div>
                <!-- Contact Links/Social Links End -->
            </div>
            <!-- Mobile Menu Inner Wrapper End -->

        </div>
        <!-- Mobile Menu Inner End -->
    </div>
    <!-- Mobile Menu End -->

{% endblock %}

home/templates/home/change.html
{% extends 'admin/change_list.html' %}
{% block extrahead %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"
            integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css"
          integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css">
    {#    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">#}

    <script>
        window.onLoad = function () {
            var ctx = document.getElementById('myChart');
            {% regroup cl.queryset|dictsort:"sell" by sell as sell_list %}
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for i in sell_list %}'{{ i.list|safe|cut:"Product:" }}',{% endfor %}],
                    datasets: [{
                        label: '# of Votes',
                        data: [{% for i in sell_list %}'{{ i.grouper }}',{% endfor %}],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        }

    </script>

{% endblock %}
{% block content %}
    <h3>Chart</h3>
    <canvas id="myChart" width="150" height="300"></canvas>
    {{ block.super }}


{% endblock %}

home/templates/home/compare.html
{% extends 'base.html' %}
{% block title %}
    مقایسه محصولات
{% endblock %}
{% block body %}

  <!-- Wishlist Section Start -->
    <div class="section section-margin">
        <div class="container">

            <div class="row">
                <div class="col-12">
                    <div class="wishlist-table table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th class="pro-thumbnail">تصویر</th>
                                    <th class="pro-title">نام محصول</th>
                                    <th class="pro-price price">قیمت</th>
                                    <th class="pro-stock">برند</th>
                                    <th class="pro-cart">امتیاز</th>
                                    <th class="pro-remove">حذف</th>
                                </tr>
                            </thead>
                            {% for i in data %}
                            <tbody>
                                <tr>
                                    <td class="pro-thumbnail"><a href="{% url 'home:detail' i.id %}"><img class="fit-image" src="{{ i.product.image.url }}" alt="Product" /></a></td>
                                    <td class="pro-title"><a href="{% url 'home:detail' i.id %}">{{ i.product.name }}</a></td>
                                    <td class="pro-price price"><span>${{ i.product.total_price }}</span></td>
                                    <td class="pro-stock"><span>{{ i.product.brand }}</span></td>
                                    <td class="pro-stock"><div class="rating"><span>{{ i.product.average }}</span><i class="fa fa-star"></i></div></td>
                                    <td class="pro-remove"><a href="{% url 'home:remove' i.product.id %}"><i class="ti-trash"></i></a></td>
                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>
                    </div>
                    <!-- Cart Button Start -->
                    <div class="cart-button-section mb-n4">

                        <!-- Cart Button left Side Start -->
                        <div class="cart-btn-lef-side mb-4">
                            <a href="{% url 'home:product' %}" class="btn btn btn-gray-deep btn-hover-primary">افزودن کالا
                                </a>
                        </div>
                        <!-- Cart Button left Side End -->


                    </div>
                    <!-- Cart Button End -->
                </div>
            </div>

        </div>
    </div>
    <!-- Wishlist Section End -->















 <!-- Scroll Top Start -->
    <a href="#" class="scroll-top show" id="scroll-top">
        <i class="arrow-top ti-angle-double-up"></i>
        <i class="arrow-bottom ti-angle-double-up"></i>
    </a>
    <!-- Scroll Top End -->

     <!-- Mobile Menu Start -->
    <div class="mobile-menu-wrapper">
        <div class="offcanvas-overlay"></div>

        <!-- Mobile Menu Inner Start -->
        <div class="mobile-menu-inner">

            <!-- Button Close Start -->
            <div class="offcanvas-btn-close">
                <i class="fa fa-times"></i>
            </div>
            <!-- Button Close End -->

            <!-- Mobile Menu Inner Wrapper Start -->
            <div class="mobile-menu-inner-wrapper">


                <!-- Mobile Menu Start -->
                <div class="mobile-navigation">
                    <nav>
                        <ul class="mobile-menu">
                            <li class="has-children">
                                <a href="{% url 'home:home' %}">خانه </a>
                            </li>
                            {% for data in category %}
                                <li class="has-children">
                                    <a href="#"> {{ data.name }}<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                                    <ul class="dropdown">
                                        {% for info in data.sub.all %}
                                            <li><a href="{{ info.get_absolute_url }}">{{ info.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}
{#                            <li class="has-children">#}
{#                                <a href="{% url 'home:product' %}">فروشگاه </a>#}
{#                            </li>#}
                            <li class="has-children">
                                <a href="{% url 'home:blog_list' %}">آموزش</a>
                            </li>
                            <li class="has-children">
                                <a href="{% url 'home:about' %}">درباره ما</a>
                            </li>
                            <li class="has-children">
                                <a href="{% url 'home:contact' %}">تماس با ما</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!-- Mobile Menu End -->


                <!-- Contact Links/Social Links Start -->
                <div class="mt-auto bottom-0">

                    <!-- Contact Links Start -->
                    <ul class="contact-links">
                        <li><i class="fa fa-phone"></i><a href="#" class="mx-1"> 0919-877-1017</a></li>
                        <li><i class="fa fa-envelope-o"></i><a href="#" class="mx-1"> petshoproyal.co@gmail.com</a></li>
                        <li><i class="fa fa-clock-o"></i> <span class="mx-1">هر روز هفته ، هر ساعت روز</span></li>
                    </ul>
                    <!-- Contact Links End -->

                    <!-- Social Widget Start -->
                    <div class="widget-social">
                        <a title="Telegram" href="https://t.me/PetshopRoyal1"><i class="fa fa-telegram"></i></a>
                        <a title="Instagram" href="https://instagram.com/petshop_royal1"><i class="icon-social-instagram"></i></a>
                        <a title="Whatsapp" href="https://wa.link/m35ti7"><i class="fa fa-whatsapp"></i></a>
                    </div>
                    <!-- Social Widget Ender -->
                </div>
                <!-- Contact Links/Social Links End -->
            </div>
            <!-- Mobile Menu Inner Wrapper End -->

        </div>
        <!-- Mobile Menu Inner End -->
    </div>
    <!-- Mobile Menu End -->





















{#    <div class="container">#}
{#        <div class="card bg-dark mt-5 p-5">#}
{#            {% for i in data %}#}
{#                <p>{{ i.product.name }}</p>#}
{#                <a href="{% url 'home:remove' i.product.id %}">remove compare</a>#}
{#            {% endfor %}#}
{#        </div>#}
{#    </div>#}
    <script>
    let prices = document.querySelectorAll(".price");
    prices.forEach((price) => {
        price.innerHTML = price.innerHTML.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    });
</script>
{% endblock %}