accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('otpregister/', views.registerotp, name='otpregister'),
    # path('login/',views.user_login,name='login'),
    # path('otp/',views.otp_view,name='otp'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='update'),
    path('change/', views.change_password, name='change'),
    path('verify/', views.verify, name='verify'),
    path('active/<uidb64>/<token>/', views.RegisterEmail.as_view(), name='active'),
    # path('reset/', views.ResetPassword.as_view(), name='reset'),
    path('reset/', views.resetpass, name='reset'),
    path('reset/done/', views.DonePassword.as_view(), name='reset_done'),
    path('confirm/<uidb64>/<token>', views.ConfirmPassword.as_view(), name='password_reset_confirm'),
    path('confirm/done/', views.Complete.as_view(), name='compelet'),
    # path('favourite/',views.favourite,name='favourite'),
    # path('history/',views.history,name='history'),
    path('view/', views.product_view, name='product_view'),
    path('login/', views.LoginOTP.as_view(), name='login'),
    path('otp/', views.otp_view, name='otp'),
    path('resetotp/', views.resetpasswordotp, name='resetotp'),
    path('resetpassword/<uidb64>/<token>', views.resetpassword, name='resetpass'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_details, name="details"),
    path("add/<int:id>/", views.cart_add, name="add_cart"),
    path("remove/<int:id>/", views.cart_remove, name="remove"),
    path("show/", views.cart_show, name="show"),
    path("add-single/<int:id>/", views.add_single, name="add-single"),
    path("remove_single/<int:id>/", views.remove_single, name="remove_single"),
    path("update-cart", views.updatecart, name="updatecart"),
    path("provinces-json/", views.get_json_province_data, name="provinces-json"),
    path("city-json/<str:city>/", views.get_json_city_data, name="models-json"),
    path("cart-count/", views.ItemcountView.as_view(), name="cart-count"),
]

home/urls.py
from django.urls import path

from . import views

app_name='home'
urlpatterns = [
    path('',views.home,name='home'),
    path('product/',views.all_product,name='product'),
    path('detail/<int:id>/',views.product_detail,name='detail'),
    path('category/<slug>/<int:id>',views.all_product,name='category'),
    path('like/<int:id>',views.product_like,name='product_like'),
    path('unlike/<int:id>',views.product_unlike,name='product_unlike'),
    path('comment/<int:id>',views.product_Comment,name='product_Comment'),
    path('reply/<int:id>/<int:comment_id>/',views.product_reply,name='product_reply'),
    path('like_comment/<int:id>',views.comment_like,name='comment_like'),
    path('search/',views.product_search,name='product_search'),
    path('favourite/<int:id>/',views.favourite_product,name='favourite'),
    path('contact/',views.contact,name='contact'),
    path('compare/',views.compare,name='compare'),
    path('about/',views.about,name='about'),
    path('add/<int:product_id>',views.add_compare,name='add'),
    path('remove/<int:product_id>',views.remove_compare,name='remove'),
    path('favourite/<int:id>', views.favourite_product, name='favourite'),
    path('blogs/', views.blog_list, name='blog_list'),  # A page listing all blogs
    path('blogs/<int:pk>/', views.blog_detail, name='blog_detail'),  # Detailed view for each blog
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.sitemaps import ProductViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'product' : ProductViewSitemap,
}


urlpatterns = [


  path('admin/', admin.site.urls),
  path('', include('home.urls', namespace='home')),
  path('accounts/', include('accounts.urls', namespace='accounts')),
  path('ckeditor/', include('ckeditor_uploader.urls')),
  path('cart/', include('cart.urls', namespace='cart')),
  path('order/', include('order.urls', namespace='order')),
  path('sitemaps.xml',sitemap,{'sitemaps':sitemaps})

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save





class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.IntegerField(null=True,blank=True)
    address = models.CharField(max_length=300,null=True,blank=True)
    profile_image = models.ImageField(upload_to='profile/',null=True,blank=True,default='01.jpg')

    def __str__(self):
        return self.user.username

def save_profile_user(sender,**kwargs):
    if kwargs['created']:
        profile_user = Profile(user=kwargs['instance'])
        profile_user.save()


post_save.connect(save_profile_user,sender=User)

order/models.py
from django.db import models
from django.contrib.auth.models import User
from home.models import *
from django.forms import ModelForm
from django_jalali.db import models as jmodels

from utils.defines import get_delivery_price



class Province(models.Model):
    name = models.CharField(max_length=100,blank=True,null=True)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100,blank=True,null=True)
    province = models.ForeignKey(Province,on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Order(models.Model):
    ONLINE='1'
    DELIVERY='2'
    CART_TO_CART='3'

    payment_method_arr = (
        (ONLINE, 'درگاه انلاین'),
        (DELIVERY, 'درب منزل'),
        (CART_TO_CART, 'کارت به کارت'),
    )

    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    create = models.DateTimeField(auto_now_add=True)
    discount = models.PositiveIntegerField(blank=True,null=True)
    phone = models.PositiveIntegerField(blank=True,null=True)
    delivery_hour = models.ForeignKey('order.DeliveryHour', models.SET_NULL, 'oo_delivery_hour', null=True)
    paid = models.BooleanField(default=False)
    tipax = models.BooleanField(default=False)
    code = models.CharField(max_length=200,null=True)
    email = models.EmailField(blank=True,null=True)
    f_name = models.CharField(max_length=100)
    l_name = models.CharField(max_length=100)
    address = models.CharField(max_length=300)
    zipcode = models.CharField(max_length=10,blank=True,null=True)
    province = models.ForeignKey(Province,on_delete=models.CASCADE,null=True,blank=True)
    city = models.ForeignKey(City,on_delete=models.CASCADE,null=True,blank=True)
    payment_method=models.CharField(max_length=1,choices=payment_method_arr,default='1')
    payment_screenshot = models.ImageField(upload_to='payment_screenshots/', blank=True, null=True) # only payment method is cart to card
    tracking_code = models.CharField(max_length=20, blank=True, null=True)
    user_confirmed= models.BooleanField(default=True)

    def __str__(self):
        if self.user:
            return self.user.username
        return f"{self.id}"

    def get_price(self):
        total = sum(i.price() for i in self.order_item.all())
        if self.city and self.city.name == 'تهران':
            if self.discount:
                discunt_price = (self.discount / 100) * total
                return int(total - discunt_price)
        elif not self.tipax:
            items = self.order_item.all()
            weight = 0
            for i in items:
                variant = i.variant
                if variant:
                    weight += i.variant.weight * i.quantity
            total += get_delivery_price(weight)
            if self.discount:
                discunt_price = (self.discount / 100) * total
                return int(total - discunt_price)
        else:
            if self.discount:
                discunt_price = (self.discount / 100) * total
                return int(total - discunt_price)

        return total


class ItemOrder(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,related_name='order_item')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants,on_delete=models.CASCADE,null=True,blank=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.user.username

    def size(self):
        return self.variant.size_variant.name

    def color(self):
        return self.variant.color_variant.name

    def price(self):
        if self.product.status != 'None':
            return self.variant.total_price * self.quantity
        else:
            return self.product.total_price * self.quantity

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['email','f_name','l_name','address','zipcode','phone','province','city']


class CheckOut(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    creditNumberCard = models.CharField(default=0,null=True,blank=True, max_length=255)
    date = models.CharField(max_length=300,null=True,blank=True)
    trackingCode = models.CharField(max_length=30,null=True,blank=True)
    trans_id = models.CharField(max_length=255,null=True,blank=True)
    invoice_id = models.CharField(max_length=255, null=True, blank=True)
    bank = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=255, null=True, blank=True)
    finalPrice = models.PositiveIntegerField(default=0,null=True,blank=True)

    def __str__(self):
        return self.order.user.username

    def final_price(self):
        return self.order.get_price()


class Coupon(models.Model):
    code = models.CharField(max_length=100,unique=True)
    active = models.BooleanField(default=False)
    start = jmodels.jDateTimeField()
    end = jmodels.jDateTimeField()
    discount = models.IntegerField()


"""
Delivery models
Mostafa Rasouli
mostafarasooli54@gmail.com
2023-12-15
"""


class DeliveryPrice(models.Model):
    from_weight = models.PositiveIntegerField()
    to_weight = models.PositiveIntegerField()
    price = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.from_weight} - {self.to_weight}'


class DeliveryHour(models.Model):
    from_hour = models.CharField(max_length=30)
    to_hour = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.from_hour} - {self.to_hour}'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from django.core.validators import RegexValidator




phone_validator = RegexValidator(
    regex=r"^09\d{9}$",
    message="Phone number must start with 09 and be exactly 11 digits long."
)



error = {
    'min_length':'tedad kam ast',
    'required':'elzam b por boudan',
}


class UserRegisterForm(forms.Form):
    # user_name=forms.CharField(error_messages=error,max_length=200,widget=forms.TextInput(attrs={'placeholder':'نام کاربری خود را وارد نمایید'}))
    # email=forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'enter email...'}))
    first_name=forms.CharField(max_length=10,min_length=3,error_messages=error)
    last_name=forms.CharField(max_length=200)
    # password_1=forms.CharField(max_length=200,widget=forms.PasswordInput(attrs={'placeholder' : 'plz pass...'}))
    # password_2=forms.CharField(max_length=200)
    phone=forms.CharField(max_length=11,required=True,validators=[phone_validator],widget=forms.TextInput(attrs={'placeholder':'تلفن خود را وارد کنید',}))
    otpcode=forms.IntegerField(required=True)

   
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if Profile.objects.filter(phone=phone).exists():
            raise forms.ValidationError('شماره تلفن تکراری است')
        return phone
    

    # def clean_email(self):
    #      email = self.cleaned_data['email']
    #      if User.objects.filter(email=email).exists():
    #          raise forms.ValidationError('email tekrari ast')
    #      return email


    # def clean_password_2(self):
    #     password1 = self.cleaned_data['password_1']
    #     password2 = self.cleaned_data['password_2']
    #     if password1 != password2 :
    #         raise forms.ValidationError('password not match')
    #     # elif len(password2) < 8:
    #     #     raise forms.ValidationError('password is short')
    #     # elif not any(x.isupper() for x in password2):
    #     #     raise forms.ValidationError('hadeaghal ....')
    #     return password1


class UserLoginForm(forms.Form):
    username = forms.CharField()
    # password = forms.CharField()
    # remember = forms.BooleanField(required=False,widget=forms.CheckboxInput())


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email','first_name','last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone','address','profile_image']


class PhoneForm(forms.Form):
    phone = forms.IntegerField()


class CodeForm(forms.Form):
    code = forms.IntegerField()















class Resetpassword(forms.Form):
    password_1=forms.CharField(max_length=200,widget=forms.PasswordInput(attrs={'placeholder' : 'رمز عبور را وارد کنید '}))
    password_2=forms.CharField(max_length=200,widget=forms.PasswordInput(attrs={'placeholder' : ' تکرار رمز عبور را وارد کنید '}))


    def clean_password_2(self):
        password1 = self.cleaned_data['password_1']
        password2 = self.cleaned_data['password_2']
        if password1 != password2 :
            raise forms.ValidationError('password not match')
        # elif len(password2) < 8:
        #     raise forms.ValidationError('password is short')
        # elif not any(x.isupper() for x in password2):
        #     raise forms.ValidationError('hadeaghal ....')
        return password1

accounts/templates/accounts/link.html
با سلام خدمت شما ،رویال پت شاپی عزیز ،لطفا روی لینک زیر کلیک کنید تا به صفحه تغییر رمز وارد شوید .
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block title %}
    پروفایل کاربری
{% endblock %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/dashbord.css' %}">
{% endblock %}
{% block body %}

<!-- My Account Section Start -->
    <div class="section section-margin">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 ">
                    <!-- My Account Page Start -->
                    <div class="myaccount-page-wrapper">
                        <div class="row">
                            <!-- My Account Tab Content Start -->
                            <div class="col-lg-10 col-md-8 mx-auto">
                                <div class="tab-content" id="myaccountContent">
                                    <!-- Single Tab Content Start -->
                                    <div class="tab-pane fade show active" id="dashboad" role="tabpanel">
                                        <div class="myaccount-content">
                                            <h3 class="title">ویرایش اطلاعات</h3>
                                            <div class="account-details-form">
                                                <form method="post">
                                                                                {% csrf_token %}
{#                                                    {{ user_form }}#}
{#                                                    {{ profile_form }}#}
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="single-input-item mb-3">
                                                                <label for="first-name" class="required mb-2">نام</label>
                                                                <input type="text" name="first_name" value={{ request.user.first_name }} maxlength="150" id="id_first_name">
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="single-input-item mb-3">
                                                                <label for="last-name" class="required mb-2">نام خانوادگی</label>
                                                                <input type="text" name="last_name" value={{ request.user.last_name }} maxlength="150" id="id_last_name">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="single-input-item mb-3">
                                                        <label for="email" class="required mb-1">ایمیل</label>
                                                        <input type="email" name="email" value={{ request.user.email }} maxlength="254" id="id_email">
                                                    </div>
                                                    <div class="single-input-item mb-3">
                                                        <label for="email" class="required mb-1">همراه</label>
                                                        <input type="number" name="phone" {% if request.user.profile.phone == None %} value="" {% else  %} value={{request.user.profile.phone}}  {% endif %} id="id_phone">
                                                    </div>
                                                    <div class="single-input-item mb-3">
                                                        <label for="email" class="required mb-1">آدرس</label>
                                                        <input type="text" name="address"  {% if request.user.profile.address == None %} value="" {% else  %} value={{request.user.profile.address}}  {% endif %} maxlength="300" id="id_address">
                                                    </div>
                                                    <div class="single-input-item single-item-button mt-6 mx-auto">
                                                        <button type="submit" class="btn btn btn-primary btn-hover-dark rounded-0">ذخیره اطلاعات</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Single Tab Content End -->
                                </div>
                            </div>
                            <!-- My Account Tab Content End -->
                        </div>
                    </div>
                    <!-- My Account Page End -->
                </div>
            </div>

        </div>
    </div>
    <!-- My Account Section End -->




































{#    <div class="container-fluid">#}
{#        <div class="row">#}
{#            <div class="col-4">#}
{##}
{#                <div class="side-menu">#}
{#                    <div class="image-container">#}
{#                        <img src="{{ profile_form.profile_image.url }}" style="width: 200px;height: 200px" alt="">#}
{#                    </div>#}
{##}
{#                    <a href="{% url 'accounts:profile' %}">Profile</a>#}
{#                    <a href="{% url 'accounts:update' %}">Update</a>#}
{#                    <a href="{% url 'accounts:change' %}">Change Password</a>#}
{#                    <a href="{% url 'accounts:history' %}">History</a>#}
{#                    <a href="{% url 'accounts:favourite' %}">Favourites</a>#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-8">#}
{#                <div class="profile">#}
{#                    <div class="card-body">#}
{#                        <h1>welcome to uodate page</h1>#}
{#                        <form method="post" enctype="multipart/form-data">#}
{#                            {% csrf_token %}#}
{#                            {{ user_form.as_p }}#}
{#                            {{ profile_form.as_p }}#}
{#                            <button type="submit">Update</button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{##}
{#    </div>#}
 <!-- Scroll Top Start -->
    <a href="#" class="scroll-top show" id="scroll-top">
        <i class="arrow-top ti-angle-double-up"></i>
        <i class="arrow-bottom ti-angle-double-up"></i>
    </a>
    <!-- Scroll Top End -->

     <!-- Mobile Menu Start -->
    <div class="mobile-menu-wrapper">
        <div class="offcanvas-overlay"></div>

        <!-- Mobile Menu Inner Start -->
        <div class="mobile-menu-inner">

            <!-- Button Close Start -->
            <div class="offcanvas-btn-close">
                <i class="fa fa-times"></i>
            </div>
            <!-- Button Close End -->

            <!-- Mobile Menu Inner Wrapper Start -->
            <div class="mobile-menu-inner-wrapper">


                <!-- Mobile Menu Start -->
    <div class="mobile-menu-wrapper">
        <div class="offcanvas-overlay"></div>

        <!-- Mobile Menu Inner Start -->
        <div class="mobile-menu-inner">

            <!-- Button Close Start -->
            <div class="offcanvas-btn-close">
                <i class="fa fa-times"></i>
            </div>
            <!-- Button Close End -->

            <!-- Mobile Menu Inner Wrapper Start -->
            <div class="mobile-menu-inner-wrapper">


                <!-- Mobile Menu Start -->
                <div class="mobile-navigation">
                    <nav>
                        <ul class="mobile-menu">
                            <li class="has-children">
                                <a href="{% url 'home:home' %}">خانه </a>
                            </li>
                            {% for data in category %}
                                <li class="has-children">
                                    <a href="#"> {{ data.name }}<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                                    <ul class="dropdown">
                                        {% for info in data.sub.all %}
                                            <li><a href="{{ info.get_absolute_url }}">{{ info.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}
{#                            <li class="has-children">#}
{#                                <a href="{% url 'home:product' %}">فروشگاه </a>#}
{#                            </li>#}
                            <li class="has-children">
                                <a href="#">آموزش(به زودی)</a>
                            </li>
                            <li class="has-children">
                                <a href="{% url 'home:about' %}">درباره ما</a>
                            </li>
                            <li class="has-children">
                                <a href="{% url 'home:contact' %}">تماس با ما</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!-- Mobile Menu End -->


                <!-- Contact Links/Social Links Start -->
                <div class="mt-auto bottom-0">

                    <!-- Contact Links Start -->
                    <ul class="contact-links">
                        <li><i class="fa fa-phone"></i><a href="#" class="mx-1"> 0919-877-1017</a></li>
                        <li><i class="fa fa-envelope-o"></i><a href="#" class="mx-1"> petshoproyal.co@gmail.com</a></li>
                        <li><i class="fa fa-clock-o"></i> <span class="mx-1">هر روز هفته ، هر ساعت روز</span></li>
                    </ul>
                    <!-- Contact Links End -->

                    <!-- Social Widget Start -->
                    <div class="widget-social">
                        <a title="Telegram" href="https://t.me/PetshopRoyal1"><i class="fa fa-telegram"></i></a>
                        <a title="Instagram" href="https://instagram.com/petshop_royal1"><i class="icon-social-instagram"></i></a>
                        <a title="Whatsapp" href="https://wa.link/m35ti7"><i class="fa fa-whatsapp"></i></a>
                    </div>
                    <!-- Social Widget Ender -->
                </div>
                <!-- Contact Links/Social Links End -->
            </div>
            <!-- Mobile Menu Inner Wrapper End -->

        </div>
        <!-- Mobile Menu Inner End -->
    </div>
    <!-- Mobile Menu End -->


                <!-- Contact Links/Social Links Start -->
                <div class="mt-auto bottom-0">

                    <!-- Contact Links Start -->
                    <ul class="contact-links">
                        <li><i class="fa fa-phone"></i><a href="#" class="mx-1"> 0919-877-1017</a></li>
                        <li><i class="fa fa-envelope-o"></i><a href="#" class="mx-1"> petshoproyal.co@gmail.com</a></li>
                        <li><i class="fa fa-clock-o"></i> <span class="mx-1">هر روز هفته ، هر ساعت روز</span></li>
                    </ul>
                    <!-- Contact Links End -->

                    <!-- Social Widget Start -->
                    <div class="widget-social">
                        <a title="Telegram" href="https://t.me/PetshopRoyal1"><i class="fa fa-telegram"></i></a>
                        <a title="Instagram" href="https://instagram.com/petshop_royal1"><i class="icon-social-instagram"></i></a>
                        <a title="Whatsapp" href="https://wa.link/m35ti7"><i class="fa fa-whatsapp"></i></a>
                    </div>
                    <!-- Social Widget Ender -->
                </div>
                <!-- Contact Links/Social Links End -->
            </div>
            <!-- Mobile Menu Inner Wrapper End -->

        </div>
        <!-- Mobile Menu Inner End -->
    </div>
    <!-- Mobile Menu End -->
{% endblock %}