accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('otpregister/', views.registerotp, name='otpregister'),
    # path('login/',views.user_login,name='login'),
    # path('otp/',views.otp_view,name='otp'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='update'),
    path('change/', views.change_password, name='change'),
    path('verify/', views.verify, name='verify'),
    path('active/<uidb64>/<token>/', views.RegisterEmail.as_view(), name='active'),
    # path('reset/', views.ResetPassword.as_view(), name='reset'),
    path('reset/', views.resetpass, name='reset'),
    path('reset/done/', views.DonePassword.as_view(), name='reset_done'),
    path('confirm/<uidb64>/<token>', views.ConfirmPassword.as_view(), name='password_reset_confirm'),
    path('confirm/done/', views.Complete.as_view(), name='compelet'),
    # path('favourite/',views.favourite,name='favourite'),
    # path('history/',views.history,name='history'),
    path('view/', views.product_view, name='product_view'),
    path('login/', views.LoginOTP.as_view(), name='login'),
    path('otp/', views.otp_view, name='otp'),
    path('resetotp/', views.resetpasswordotp, name='resetotp'),
    path('resetpassword/<uidb64>/<token>', views.resetpassword, name='resetpass'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_details, name="details"),
    path("add/<int:id>/", views.cart_add, name="add_cart"),
    path("remove/<int:id>/", views.cart_remove, name="remove"),
    path("show/", views.cart_show, name="show"),
    path("add-single/<int:id>/", views.add_single, name="add-single"),
    path("remove_single/<int:id>/", views.remove_single, name="remove_single"),
    path("update-cart", views.updatecart, name="updatecart"),
    path("provinces-json/", views.get_json_province_data, name="provinces-json"),
    path("city-json/<str:city>/", views.get_json_city_data, name="models-json"),
    path("cart-count/", views.ItemcountView.as_view(), name="cart-count"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.sitemaps import ProductViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'product' : ProductViewSitemap,
}


urlpatterns = [


  path('admin/', admin.site.urls),
  path('', include('home.urls', namespace='home')),
  path('accounts/', include('accounts.urls', namespace='accounts')),
  path('ckeditor/', include('ckeditor_uploader.urls')),
  path('cart/', include('cart.urls', namespace='cart')),
  path('order/', include('order.urls', namespace='order')),
  path('sitemaps.xml',sitemap,{'sitemaps':sitemaps})

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href="{% static 'body.css' %}">
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="enamad" content="73263192"/>
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}">

<!-- Preloader to increase Performance -->
    <link
      rel="preload"
      as="image"
      href="{% static 'assets/images/slider/slide 1.png' %}"
      imagesrcset="
        {% static 'assets/images/slider/slide 1.png' %} 1x,
        {% static 'assets/images/slider/slide2.png' %} 2x
        {% static 'assets/images/slider/slide 3.png' %} 3x
        {% static 'assets/images/slider/slide4.png' %} 4x
      "
      imagesizes="100vw"
    />

    <!-- Vendor CSS (Icon Font) -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/fontawesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/vendor/simple-line-icons.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/vendor/themify-icons-min.css' %}"/>




    <!-- Plugins CSS (All Plugins Files) -->
    <link rel="stylesheet" href="{% static 'assets/css/plugins/swiper-bundle.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/plugins/animate.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/plugins/lightgallery.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/plugins/aos.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/plugins/nice-select.min.css' %}"/>
    <link rel="stylesheet" href="https://unpkg.com/persian-datepicker@1.2.0/dist/css/persian-datepicker.css">
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/persian-date.js' %}"></script>
    <script src="{% static 'assets/js/persian-date.min.js' %}"></script>
    <script src="https://unpkg.com/persian-date@1.1.0/dist/persian-date.js"></script>
    <script src="https://unpkg.com/persian-datepicker@1.2.0/dist/js/persian-datepicker.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-element-bundle.min.js"></script>



    <!-- Main Style CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}"/>

    {#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css">#}
    {#    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">#}
    {#    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>#}

    {% block css %}{% endblock %}
    {#     <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>#}

    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>#}


    {#    <link rel='stylesheet' href='https://sachinchoolur.github.io/lightslider/dist/css/lightslider.css'>#}

</head>
<body class="main">
{% include 'navbar.html' %}
{% include 'message.html' %}

{% block body %}{% endblock %}


{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>#}

{% block script %}{% endblock %}
{#    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>#}

{% include 'footer.html' %}


<!-- Global Vendor, plugins JS -->

<!-- Vendor JS -->


<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
{#<script src="{% static 'assets/js/vendor/jquery-3.6.0.min.js' %}"></script>#}
<script src="{% static 'assets/js/vendor/jquery-migrate-3.3.2.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/modernizr-3.11.2.min.js' %}"></script>


<!-- Plugins JS -->


<script src="{% static 'assets/js/plugins/aos.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery-ui.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/nice-select.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/countdown.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/lightgallery-all.min.js' %}"></script>


<!-- Use the minified version files listed below for better performance and remove the files listed above -->

<!--
<script src="assets/js/vendor.min.js"></script>
<script src="assets/js/plugins.min.js"></script>
-->
<script>
    function getParentLang(node) { var defaultLang = 'fa'; var currLang = null; while(currLang === null && node.parentNode) { if (node.getAttribute && node.getAttribute('lang')) { currLang = node.getAttribute('lang'); } node = node.parentNode; } return currLang || defaultLang; } function TraceNodes(e) { if (e.nodeType == 3 && getParentLang(e) === 'fa' /* Persian */) { e.nodeValue = e.nodeValue.toPersianDigit(); } else { for (var t = 0; t < e.childNodes.length; t++) { TraceNodes(e.childNodes[t]); } } } String.prototype.toPersianDigit = function(e) { return this.replace(/\d+/g, function(t) { var n = [], r = []; for (var i = 0; i < t.length; i++) { n.push(t.charCodeAt(i)) } for (var s = 0; s < n.length; s++) { r.push(String.fromCharCode(n[s] + (!!e && e == true ? 1584 : 1728))) } return r.join("") }) }; TraceNodes(document);
</script>
<!--Main JS-->
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

templates/footer.html
{% load static %}

<!-- Footer Section Start -->
<footer class="section footer-section">

    <!-- Footer Top Start -->
    <div class="footer-top bg-bright section-padding">
        <div class="container">

            <!-- ===== ردیف اصلی (5 ستون) ===== -->
            <div class="row mb-n6 justify-content-between">

                <!-- ستون ۵: درباره ما -->
                <div class="col-12 col-sm-12 col-md-2 mb-8 order-md-1">
                    <h2 class="widget-title">درباره ما</h2>
                    <p class="desc-content">
                        پت شاپ رویال از سال 1399 با هدف بهبود کیفیت زندگی پت‌های داخل ایران
                        و عرضه برترین محصولات غذایی سگ و گربه همراه شما است.
                    </p>
                </div>

                <!-- ستون ۴: لینک‌های کاربردی -->
                <div class="col-12 col-sm-6 col-md-3 mb-8 order-md-2 ">
                    <h2 class="widget-title">شبکه های اجتماعی</h2>
                    <div class="widget-social justify-content-center">
                        <a title="Telegram" href="https://t.me/PetshopRoyal1"><i class="fa fa-telegram fs-2"></i></a>
                        <a title="Instagram" href="https://instagram.com/petshop_royal1"><i
                                class="icon-social-instagram fs-2"></i></a>
                        <a title="Whatsapp" href="https://wa.link/m35ti7"><i class="fa fa-whatsapp fs-2"></i></a>
                    </div>
                </div>

                <!-- ستون ۳: تماس با ما -->
                <div class="col-12 col-sm-6 col-md-3 mb-8 order-md-3">
                    <h2 class="widget-title">تماس با ما</h2>
                    <ul class="widget-list">
                        <li><i class="fa fa-phone"></i> <a class="mx-1">0919-877-1017</a></li>
                        <li><i class="fa fa-envelope-o"></i> <a class="mx-1">petshoproyal.co@gmail.com</a></li>
                    </ul>
                </div>

                <!-- ستون ۲: منو سریع -->
                <div class="col-12 col-sm-6 col-md-2 mb-8 order-md-4">
                    <h2 class="widget-title">منو سریع</h2>
                    <ul class="widget-list">
                        <li><a href="{% url 'accounts:login' %}">ورود</a></li>
                        <li><a href="{% url 'accounts:register' %}">ثبت نام</a></li>
                        <li><a href="{% url 'accounts:profile' %}">پنل کاربری</a></li>
                        <li><a href="{% url 'cart:details' %}">سبد خرید</a></li>
                    </ul>
                </div>


                <!-- ستون ۱: Developer Credit -->
                <div class="col-12 col-sm-6 col-md-2 mb-8 text-center order-md-5">
                    <!-- 1) Logo on top -->
                    <img src="{% static 'assets/images/team/ScriptOrbit1.png' %}"
                         alt="ScriptOrbit"
                         class="mb-2 mx-auto"
                         style="width:58px; height:58px;">

                    <!-- 2) Credit text -->
                    <p class="mb-2">توسعه و طراحی توسط تیم</p>

                    <!-- 3) Link to site -->
                    <p class="mb-2" style="display: flex;align-items: center;justify-content: center;column-gap: 3px">
                        <a title="Instagram"
                           href="https://www.instagram.com/scriptorbit"
                           class="d-inline-block developer-link">
                            <i class="icon-social-instagram fs-5"></i>
                        </a>
                        <a href="https://scriptorbit.com"
                           target="_blank"
                           class="developer-link">
                            ScriptOrbit

                        </a>
                    </p>


                </div>
            </div>

            <div class="row mb-n8">
                <div class="col-12 col-sm-6 col-lg-3 mb-8 ">
                    <div class="single-footer-widget aos-init aos-animate text-center">
                        <a referrerpolicy='origin' target='_blank'
                           href='https://trustseal.enamad.ir/u?id=401997&Code=HR39rhGaFb5Sa35VB47IduBFUfaD5KnT'><img
                                referrerpolicy='origin'
                                src='https://trustseal.enamad.ir/logo.aspx?id=401997&Code=HR39rhGaFb5Sa35VB47IduBFUfaD5KnT'
                                alt='' style='cursor:pointer' Code='HR39rhGaFb5Sa35VB47IduBFUfaD5KnT'></a>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- Footer Top End -->

    <!-- Footer Bottom Start -->
    <div class="footer-bottom bg-light pt-4 pb-4">
        <div class="container">
            <div class="row align-items-center mb-n4">
                <div class="col-12 text-center mb-4">
                    <p class="mb-0">
                        تمام حقوق این سایت متعلق به فروشگاه پت شاپ رویال است. © 2021‑2025
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Bottom End -->

</footer>

templates/message.html
{% if messages %}
    <!-- Breadcrumb Area Start -->
    <div class="section breadcrumb-area bg-bright">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="breadcrumb-wrapper">
                        {% for msg in messages %}
                            <h2 {% if msg.tags %} class="breadcrumb-title alert alert-{{ msg.tags }}" {% endif %}>{{ msg }}</h2>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End -->


{% endif %}